import type { TournamentConfig } from './types';

/**
 * World Cup 2026 — 48 teams, groups A–L. Hosts: USA, Canada, Mexico.
 * Group-stage fixtures follow published schedule order (e.g. USA TODAY, Mar 26 2026), with play-off
 * winners resolved to: Czech Republic, Bosnia and Herzegovina, Türkiye, Sweden, Iraq, DR Congo.
 * Display names must match backend match data (homeTeam, awayTeam, winnerTeam).
 * Code is ISO 3166-1 alpha-2 for react-world-flags.
 */
export const worldCup2026Config: TournamentConfig = {
  key: 'world-cup-2026',
  label: 'World Cup 2026',
  teams: [
    // Hosts
    { displayName: 'United States', code: 'us', shortName: 'USA' },
    { displayName: 'Canada', code: 'ca', shortName: 'CAN' },
    { displayName: 'Mexico', code: 'mx', shortName: 'MEX' },
    // CONMEBOL
    { displayName: 'Argentina', code: 'ar', shortName: 'ARG' },
    { displayName: 'Brazil', code: 'br', shortName: 'BRA' },
    { displayName: 'Uruguay', code: 'uy', shortName: 'URU' },
    { displayName: 'Colombia', code: 'co', shortName: 'COL' },
    { displayName: 'Ecuador', code: 'ec', shortName: 'ECU' },
    { displayName: 'Paraguay', code: 'py', shortName: 'PAR' },
    // AFC
    { displayName: 'Japan', code: 'jp', shortName: 'JPN' },
    { displayName: 'South Korea', code: 'kr', shortName: 'KOR' },
    { displayName: 'Australia', code: 'au', shortName: 'AUS' },
    { displayName: 'Iran', code: 'ir', shortName: 'IRN' },
    { displayName: 'Iraq', code: 'iq', shortName: 'IRQ' },
    { displayName: 'Saudi Arabia', code: 'sa', shortName: 'KSA' },
    { displayName: 'Qatar', code: 'qa', shortName: 'QAT' },
    { displayName: 'Jordan', code: 'jo', shortName: 'JOR' },
    { displayName: 'Uzbekistan', code: 'uz', shortName: 'UZB' },
    // CAF
    { displayName: 'Egypt', code: 'eg', shortName: 'EGY' },
    { displayName: 'Morocco', code: 'ma', shortName: 'MAR' },
    { displayName: 'DR Congo', code: 'cd', shortName: 'COD' },
    { displayName: 'Tunisia', code: 'tn', shortName: 'TUN' },
    { displayName: 'Algeria', code: 'dz', shortName: 'ALG' },
    { displayName: 'Ghana', code: 'gh', shortName: 'GHA' },
    { displayName: 'Senegal', code: 'sn', shortName: 'SEN' },
    { displayName: 'Ivory Coast', code: 'ci', shortName: 'CIV' },
    { displayName: 'South Africa', code: 'za', shortName: 'RSA' },
    { displayName: 'Cape Verde', code: 'cv', shortName: 'CPV' },
    // OFC
    { displayName: 'New Zealand', code: 'nz', shortName: 'NZL' },
    // CONCACAF (non-host)
    { displayName: 'Curaçao', code: 'cw', shortName: 'CUW' },
    { displayName: 'Haiti', code: 'ht', shortName: 'HAI' },
    { displayName: 'Panama', code: 'pa', shortName: 'PAN' },
    // UEFA
    { displayName: 'England', code: 'gb', shortName: 'ENG' },
    { displayName: 'France', code: 'fr', shortName: 'FRA' },
    { displayName: 'Germany', code: 'de', shortName: 'GER' },
    { displayName: 'Spain', code: 'es', shortName: 'ESP' },
    { displayName: 'Portugal', code: 'pt', shortName: 'POR' },
    { displayName: 'Netherlands', code: 'nl', shortName: 'NED' },
    { displayName: 'Belgium', code: 'be', shortName: 'BEL' },
    { displayName: 'Croatia', code: 'hr', shortName: 'CRO' },
    { displayName: 'Switzerland', code: 'ch', shortName: 'SUI' },
    { displayName: 'Austria', code: 'at', shortName: 'AUT' },
    { displayName: 'Norway', code: 'no', shortName: 'NOR' },
    { displayName: 'Scotland', code: 'gb', shortName: 'SCO' },
    { displayName: 'Sweden', code: 'se', shortName: 'SWE' },
    { displayName: 'Türkiye', code: 'tr', shortName: 'TUR' },
    { displayName: 'Czech Republic', code: 'cz', shortName: 'CZE' },
    { displayName: 'Bosnia and Herzegovina', code: 'ba', shortName: 'BIH' },
  ],
  maxRounds: 8,
  rounds: [
    {
      roundNumber: 1,
      label: 'Group Stage (Matchday 1)',
      pickDeadline: '2026-06-11T15:00:00-04:00',
      matches: [
        { homeTeam: 'Mexico', awayTeam: 'South Africa' },
        { homeTeam: 'South Korea', awayTeam: 'Czech Republic' },
        { homeTeam: 'Canada', awayTeam: 'Bosnia and Herzegovina' },
        { homeTeam: 'United States', awayTeam: 'Paraguay' },
        { homeTeam: 'Brazil', awayTeam: 'Morocco' },
        { homeTeam: 'Australia', awayTeam: 'Türkiye' },
        { homeTeam: 'Haiti', awayTeam: 'Scotland' },
        { homeTeam: 'Qatar', awayTeam: 'Switzerland' },
        { homeTeam: 'Germany', awayTeam: 'Curaçao' },
        { homeTeam: 'Ivory Coast', awayTeam: 'Ecuador' },
        { homeTeam: 'Netherlands', awayTeam: 'Japan' },
        { homeTeam: 'Sweden', awayTeam: 'Tunisia' },
        { homeTeam: 'Spain', awayTeam: 'Cape Verde' },
        { homeTeam: 'Belgium', awayTeam: 'Egypt' },
        { homeTeam: 'Saudi Arabia', awayTeam: 'Uruguay' },
        { homeTeam: 'Iran', awayTeam: 'New Zealand' },
        { homeTeam: 'France', awayTeam: 'Senegal' },
        { homeTeam: 'Iraq', awayTeam: 'Norway' },
        { homeTeam: 'Argentina', awayTeam: 'Algeria' },
        { homeTeam: 'Austria', awayTeam: 'Jordan' },
        { homeTeam: 'Portugal', awayTeam: 'DR Congo' },
        { homeTeam: 'England', awayTeam: 'Croatia' },
        { homeTeam: 'Ghana', awayTeam: 'Panama' },
        { homeTeam: 'Uzbekistan', awayTeam: 'Colombia' },
      ],
    },
    {
      roundNumber: 2,
      label: 'Group Stage (Matchday 2)',
      pickDeadline: '2026-06-18T12:00:00-04:00',
      matches: [
        { homeTeam: 'Czech Republic', awayTeam: 'South Africa' },
        { homeTeam: 'Switzerland', awayTeam: 'Bosnia and Herzegovina' },
        { homeTeam: 'Canada', awayTeam: 'Qatar' },
        { homeTeam: 'Mexico', awayTeam: 'South Korea' },
        { homeTeam: 'United States', awayTeam: 'Australia' },
        { homeTeam: 'Scotland', awayTeam: 'Morocco' },
        { homeTeam: 'Brazil', awayTeam: 'Haiti' },
        { homeTeam: 'Türkiye', awayTeam: 'Paraguay' },
        { homeTeam: 'Netherlands', awayTeam: 'Sweden' },
        { homeTeam: 'Germany', awayTeam: 'Ivory Coast' },
        { homeTeam: 'Ecuador', awayTeam: 'Curaçao' },
        { homeTeam: 'Tunisia', awayTeam: 'Japan' },
        { homeTeam: 'Spain', awayTeam: 'Saudi Arabia' },
        { homeTeam: 'Belgium', awayTeam: 'Iran' },
        { homeTeam: 'Uruguay', awayTeam: 'Cape Verde' },
        { homeTeam: 'New Zealand', awayTeam: 'Egypt' },
        { homeTeam: 'Argentina', awayTeam: 'Austria' },
        { homeTeam: 'France', awayTeam: 'Iraq' },
        { homeTeam: 'Norway', awayTeam: 'Senegal' },
        { homeTeam: 'Jordan', awayTeam: 'Algeria' },
        { homeTeam: 'Portugal', awayTeam: 'Uzbekistan' },
        { homeTeam: 'England', awayTeam: 'Ghana' },
        { homeTeam: 'Panama', awayTeam: 'Croatia' },
        { homeTeam: 'Colombia', awayTeam: 'DR Congo' },
      ],
    },
    {
      roundNumber: 3,
      label: 'Group Stage (Matchday 3)',
      pickDeadline: '2026-06-24T15:00:00-04:00',
      matches: [
        { homeTeam: 'Canada', awayTeam: 'Switzerland' },
        { homeTeam: 'Bosnia and Herzegovina', awayTeam: 'Qatar' },
        { homeTeam: 'Scotland', awayTeam: 'Brazil' },
        { homeTeam: 'Morocco', awayTeam: 'Haiti' },
        { homeTeam: 'Mexico', awayTeam: 'Czech Republic' },
        { homeTeam: 'South Korea', awayTeam: 'South Africa' },
        { homeTeam: 'Ecuador', awayTeam: 'Germany' },
        { homeTeam: 'Curaçao', awayTeam: 'Ivory Coast' },
        { homeTeam: 'Tunisia', awayTeam: 'Netherlands' },
        { homeTeam: 'Japan', awayTeam: 'Sweden' },
        { homeTeam: 'United States', awayTeam: 'Türkiye' },
        { homeTeam: 'Paraguay', awayTeam: 'Australia' },
        { homeTeam: 'Norway', awayTeam: 'France' },
        { homeTeam: 'Senegal', awayTeam: 'Iraq' },
        { homeTeam: 'New Zealand', awayTeam: 'Belgium' },
        { homeTeam: 'Egypt', awayTeam: 'Iran' },
        { homeTeam: 'Uruguay', awayTeam: 'Spain' },
        { homeTeam: 'Cape Verde', awayTeam: 'Saudi Arabia' },
        { homeTeam: 'Panama', awayTeam: 'England' },
        { homeTeam: 'Croatia', awayTeam: 'Ghana' },
        { homeTeam: 'Colombia', awayTeam: 'Portugal' },
        { homeTeam: 'DR Congo', awayTeam: 'Uzbekistan' },
        { homeTeam: 'Jordan', awayTeam: 'Argentina' },
        { homeTeam: 'Algeria', awayTeam: 'Austria' },
      ],
    },
    { roundNumber: 4, label: 'Round of 32', pickDeadline: '2026-06-28T15:00:00-04:00', matches: [] },
    { roundNumber: 5, label: 'Round of 16', pickDeadline: '2026-07-04T15:00:00-04:00', matches: [] },
    { roundNumber: 6, label: 'Quarter-finals', pickDeadline: '2026-07-09T15:00:00-04:00', matches: [] },
    { roundNumber: 7, label: 'Semi-finals', pickDeadline: '2026-07-14T15:00:00-04:00', matches: [] },
    { roundNumber: 8, label: 'Final', pickDeadline: '2026-07-19T15:00:00-04:00', matches: [] },
  ],
};
